/**
 * Every named natural satellite of Mars, Jupiter, Saturn, Uranus, Neptune and
 * Pluto, in the same shape as the entries in bodies-data.js. The thirteen moons
 * already carried there — the Galileans, Titan, the mid-sized Saturnians,
 * Triton, Charon and our own Moon — are deliberately absent from this list.
 *
 * Orbits: semi-major axes, periods, inclinations and eccentricities are the JPL
 * Solar System Dynamics mean elements (ssd.jpl.nasa.gov/sats/elem/), radii the
 * JPL physical parameters table (ssd.jpl.nasa.gov/sats/phys_par/) where a value
 * exists there. JPL quotes regular satellites against the parent's Laplace
 * plane, which for anything close in is the equator to within a fraction of a
 * degree, and irregular satellites against the ecliptic. The two frames are
 * mixed here, as they are in every published table, because for a captured moon
 * fifteen million kilometres out the parent's equator is not the plane the orbit
 * actually cares about. Retrograde motion is carried as an inclination past 90
 * degrees, the same convention bodies-data.js uses for Triton.
 *
 * Radii: bodies smaller than roughly 10 km have never been resolved. Their radii
 * here are derived from absolute magnitude assuming the 0.04 albedo typical of a
 * dark captured body, which is the standard estimate and is good to a factor of
 * about 1.3. Every irregular satellite below 10 km in this file — most of the
 * Jovian Ananke, Carme and Pasiphae groups, and most of the Saturnian Norse
 * group — is such an estimate rather than a measurement.
 *
 * Rotation: regular satellites are tidally locked, so rotationHours is simply
 * the orbital period. Irregular satellites are not locked and spin in hours, but
 * only a few dozen have measured light curves; those are given their real spin
 * and flagged. The rest fall back to the orbital period, which is wrong but
 * harmless — they are a handful of pixels across from any viewpoint that puts
 * the parent in frame.
 *
 * Terrain parameters mean what they mean in bodies-data.js. Two things drive
 * most of the choices: a body under about 100 km across is held together by
 * cohesion rather than gravity and is lumpy rather than round, which shows up as
 * high roughness; and the ice moons close in to Saturn are continually dusted
 * with ring material, which makes them the brightest surfaces in the file.
 */

import { applyMeasuredAxes } from './figures.js';

export const MOONS = [
  // Mars. Both are dark, carbonaceous, and battered — captured asteroids or
  // reaccreted impact debris, argued either way for fifty years.
  {
    key: 'phobos',
    name: 'Phobos',
    parent: 'mars',
    radiusKm: 11.08,
    rotationHours: 7.6488,
    orbitKm: 9375,
    orbitDays: 0.3187,
    orbitInclDeg: 1.1,
    // Stickney is 9 km across on an 11 km body, so the largest craters here are
    // a substantial fraction of the whole moon.
    craterFreq: 28,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.68,
    roughness: 0.26,
    photometry: 1,
    // Geometric albedo 0.07, among the darkest surfaces in the solar system.
    albedoBoost: 0.6,
  },
  {
    key: 'deimos',
    name: 'Deimos',
    parent: 'mars',
    radiusKm: 6.2,
    rotationHours: 30.3,
    orbitKm: 23457,
    orbitDays: 1.2625,
    orbitInclDeg: 1.8,
    // Craters here are largely buried under loose regolith, so the surface reads
    // smoother than Phobos despite being just as old.
    craterFreq: 26,
    craterOctaves: 5,
    craterDepth: 0.14,
    craterDensity: 0.5,
    roughness: 0.24,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // Jupiter: the four inner moons, which feed the ring system.
  {
    key: 'metis',
    name: 'Metis',
    parent: 'jupiter',
    radiusKm: 21.5,
    rotationHours: 7.0747,
    orbitKm: 128000,
    orbitDays: 0.294779,
    craterFreq: 45,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'adrastea',
    name: 'Adrastea',
    parent: 'jupiter',
    radiusKm: 8.2,
    rotationHours: 7.1582,
    orbitKm: 129000,
    orbitDays: 0.29826,
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'amalthea',
    name: 'Amalthea',
    parent: 'jupiter',
    radiusKm: 83.5,
    rotationHours: 11.998,
    orbitKm: 181400,
    orbitDays: 0.499918,
    orbitInclDeg: 0.4,
    // Density below that of water: a rubble pile, not a solid body, and probably
    // assembled somewhere colder than its present orbit.
    craterFreq: 90,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.65,
    roughness: 0.3,
    photometry: 1,
    // Distinctly red, the reddest object in the Jovian system, and dark with it.
    albedoBoost: 0.7,
  },
  {
    key: 'thebe',
    name: 'Thebe',
    parent: 'jupiter',
    radiusKm: 49.3,
    rotationHours: 16.2265,
    orbitKm: 221900,
    orbitDays: 0.676105,
    orbitInclDeg: 1.1,
    craterFreq: 70,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.65,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.7,
  },

  // Themisto orbits alone between the inner moons and the Himalia group, with no
  // known relatives.
  {
    key: 'themisto',
    name: 'Themisto',
    parent: 'jupiter',
    radiusKm: 4.5,
    rotationHours: 3119.2,
    orbitKm: 7397000,
    orbitDays: 129.9681,
    orbitInclDeg: 44.3,
    orbitEcc: 0.257,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // The Himalia group: prograde, clustered near 28 degrees, and probably the
  // debris of a single captured asteroid broken up by a later moon-moon
  // collision — the fragments are too evenly sized for an impactor to explain.
  {
    key: 'leda',
    name: 'Leda',
    parent: 'jupiter',
    radiusKm: 10.8,
    rotationHours: 5767.8,
    orbitKm: 11145200,
    orbitDays: 240.3264,
    orbitInclDeg: 28.2,
    orbitEcc: 0.162,
    craterFreq: 40,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'ersa',
    name: 'Ersa',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 5966.8,
    orbitKm: 11399400,
    orbitDays: 248.6153,
    orbitInclDeg: 29.0,
    orbitEcc: 0.117,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'himalia',
    name: 'Himalia',
    parent: 'jupiter',
    radiusKm: 85.0,
    // Measured light curve, not a locked rotation: nothing this far out is
    // locked, and Himalia turns roughly once every eight hours.
    rotationHours: 7.7819,
    orbitKm: 11439000,
    orbitDays: 249.909,
    orbitInclDeg: 28.4,
    orbitEcc: 0.16,
    craterFreq: 95,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.24,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'pandia',
    name: 'Pandia',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 6029.6,
    orbitKm: 11479600,
    orbitDays: 251.2319,
    orbitInclDeg: 28.9,
    orbitEcc: 0.178,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'lysithea',
    name: 'Lysithea',
    parent: 'jupiter',
    radiusKm: 21.1,
    rotationHours: 6204.1,
    orbitKm: 11699100,
    orbitDays: 258.5035,
    orbitInclDeg: 27.7,
    orbitEcc: 0.117,
    craterFreq: 50,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'elara',
    name: 'Elara',
    parent: 'jupiter',
    radiusKm: 40.0,
    rotationHours: 6213.3,
    orbitKm: 11710700,
    orbitDays: 258.8861,
    orbitInclDeg: 27.8,
    orbitEcc: 0.212,
    craterFreq: 65,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'dia',
    name: 'Dia',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 6653.9,
    orbitKm: 12257900,
    orbitDays: 277.2472,
    orbitInclDeg: 29.1,
    orbitEcc: 0.232,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.65,
  },

  // Carpo and Valetudo are prograde loners on wild orbits. Carpo's inclination
  // is high enough to drive a Lidov-Kozai cycle that swings its eccentricity
  // between 0.19 and 0.69; Valetudo's path crosses the retrograde swarm, so it
  // is on course to hit something eventually.
  {
    key: 'carpo',
    name: 'Carpo',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 10905.6,
    orbitKm: 17039500,
    orbitDays: 454.4,
    orbitInclDeg: 53.3,
    orbitEcc: 0.415,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'valetudo',
    name: 'Valetudo',
    parent: 'jupiter',
    radiusKm: 0.5,
    rotationHours: 12529.8,
    orbitKm: 18690100,
    orbitDays: 522.0743,
    orbitInclDeg: 34.5,
    orbitEcc: 0.217,
    craterFreq: 18,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.35,
    photometry: 1,
    albedoBoost: 0.65,
  },

  // The Ananke group: retrograde, spread over 19-22 million km at inclinations
  // near 150 degrees, mostly grey, and thought to be the remains of a captured
  // asteroid shattered by a passing planetesimal rather than by another moon.
  {
    key: 'euporie',
    name: 'Euporie',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 13108.3,
    orbitKm: 19261900,
    orbitDays: 546.1778,
    orbitInclDeg: 145.5,
    orbitEcc: 0.148,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'eupheme',
    name: 'Eupheme',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 14671.7,
    orbitKm: 20763400,
    orbitDays: 611.316,
    orbitInclDeg: 147.9,
    orbitEcc: 0.234,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'mneme',
    name: 'Mneme',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 14726.6,
    orbitKm: 20815800,
    orbitDays: 613.6104,
    orbitInclDeg: 147.8,
    orbitEcc: 0.24,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'euanthe',
    name: 'Euanthe',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 14734.3,
    orbitKm: 20822900,
    orbitDays: 613.9278,
    orbitInclDeg: 148.1,
    orbitEcc: 0.243,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'harpalyke',
    name: 'Harpalyke',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 14802.8,
    orbitKm: 20887500,
    orbitDays: 616.7833,
    orbitInclDeg: 147.8,
    orbitEcc: 0.239,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'orthosie',
    name: 'Orthosie',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 14813.6,
    orbitKm: 20897800,
    orbitDays: 617.2347,
    orbitInclDeg: 144.2,
    orbitEcc: 0.294,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'helike',
    name: 'Helike',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 14828.7,
    orbitKm: 20911400,
    orbitDays: 617.8625,
    orbitInclDeg: 154.4,
    orbitEcc: 0.155,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'praxidike',
    name: 'Praxidike',
    parent: 'jupiter',
    radiusKm: 3.5,
    rotationHours: 14849.3,
    orbitKm: 20931100,
    orbitDays: 618.7229,
    orbitInclDeg: 148.2,
    orbitEcc: 0.245,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'thelxinoe',
    name: 'Thelxinoe',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 14893.1,
    orbitKm: 20972300,
    orbitDays: 620.5458,
    orbitInclDeg: 150.7,
    orbitEcc: 0.229,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'thyone',
    name: 'Thyone',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 14894.1,
    orbitKm: 20972700,
    orbitDays: 620.5875,
    orbitInclDeg: 147.6,
    orbitEcc: 0.235,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'ananke',
    name: 'Ananke',
    parent: 'jupiter',
    radiusKm: 14.6,
    rotationHours: 14954.6,
    orbitKm: 21029500,
    orbitDays: 623.1097,
    orbitInclDeg: 147.6,
    orbitEcc: 0.238,
    craterFreq: 45,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.29,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'iocaste',
    name: 'Iocaste',
    parent: 'jupiter',
    radiusKm: 2.5,
    rotationHours: 14989.1,
    orbitKm: 21062300,
    orbitDays: 624.5479,
    orbitInclDeg: 148.7,
    orbitEcc: 0.223,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'hermippe',
    name: 'Hermippe',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 15033.1,
    orbitKm: 21103600,
    orbitDays: 626.3799,
    orbitInclDeg: 150.2,
    orbitEcc: 0.22,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // The Carme group, with the Pasiphae members interleaved by distance. Carme's
  // family is the tightest in the solar system — every member sits within a
  // degree of 164.6 and shares the same light red colour, which points to a
  // single D-type progenitor, quite possibly a Jupiter trojan. The Pasiphae
  // group by contrast is dispersed and its colours vary, so it has probably been
  // hit more than once.
  {
    key: 'philophrosyne',
    name: 'Philophrosyne',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 16660.9,
    orbitKm: 22600200,
    orbitDays: 694.2042,
    orbitInclDeg: 146.1,
    orbitEcc: 0.221,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'pasithee',
    name: 'Pasithee',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 16929.8,
    orbitKm: 22840800,
    orbitDays: 705.409,
    orbitInclDeg: 164.5,
    orbitEcc: 0.274,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'eurydome',
    name: 'Eurydome',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 16988.6,
    orbitKm: 22894500,
    orbitDays: 707.8569,
    orbitInclDeg: 148.9,
    orbitEcc: 0.287,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'chaldene',
    name: 'Chaldene',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 17024.7,
    orbitKm: 22926300,
    orbitDays: 709.3625,
    orbitInclDeg: 164.7,
    orbitEcc: 0.261,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'isonoe',
    name: 'Isonoe',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 17079.8,
    orbitKm: 22976300,
    orbitDays: 711.6604,
    orbitInclDeg: 164.9,
    orbitEcc: 0.249,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'kallichore',
    name: 'Kallichore',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 17126.2,
    orbitKm: 23017100,
    orbitDays: 713.5931,
    orbitInclDeg: 164.7,
    orbitEcc: 0.253,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'erinome',
    name: 'Erinome',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 17137.3,
    orbitKm: 23027200,
    orbitDays: 714.0542,
    orbitInclDeg: 164.3,
    orbitEcc: 0.272,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'kale',
    name: 'Kale',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 17160.4,
    orbitKm: 23047800,
    orbitDays: 715.016,
    orbitInclDeg: 164.6,
    orbitEcc: 0.262,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'eirene',
    name: 'Eirene',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 17164.6,
    orbitKm: 23051300,
    orbitDays: 715.191,
    orbitInclDeg: 164.7,
    orbitEcc: 0.263,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'aitne',
    name: 'Aitne',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 17172.9,
    orbitKm: 23059400,
    orbitDays: 715.5396,
    orbitInclDeg: 164.5,
    orbitEcc: 0.273,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'eukelade',
    name: 'Eukelade',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 17176.5,
    orbitKm: 23062400,
    orbitDays: 715.6868,
    orbitInclDeg: 164.7,
    orbitEcc: 0.274,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'arche',
    name: 'Arche',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 17210.5,
    orbitKm: 23093200,
    orbitDays: 717.1056,
    orbitInclDeg: 164.5,
    orbitEcc: 0.263,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'taygete',
    name: 'Taygete',
    parent: 'jupiter',
    radiusKm: 2.5,
    rotationHours: 17222.2,
    orbitKm: 23103400,
    orbitDays: 717.5917,
    orbitInclDeg: 164.7,
    orbitEcc: 0.257,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'carme',
    name: 'Carme',
    parent: 'jupiter',
    radiusKm: 23.4,
    rotationHours: 17262.7,
    orbitKm: 23139200,
    orbitDays: 719.2806,
    orbitInclDeg: 164.6,
    orbitEcc: 0.261,
    craterFreq: 50,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'herse',
    name: 'Herse',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 17271.0,
    orbitKm: 23146700,
    orbitDays: 719.6264,
    orbitInclDeg: 164.4,
    orbitEcc: 0.258,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'kalyke',
    name: 'Kalyke',
    parent: 'jupiter',
    radiusKm: 3.5,
    rotationHours: 17440.8,
    orbitKm: 23298000,
    orbitDays: 726.7007,
    orbitInclDeg: 164.7,
    orbitEcc: 0.261,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'hegemone',
    name: 'Hegemone',
    parent: 'jupiter',
    radiusKm: 1.5,
    rotationHours: 17490.6,
    orbitKm: 23342600,
    orbitDays: 728.7743,
    orbitInclDeg: 152.5,
    orbitEcc: 0.357,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'pasiphae',
    name: 'Pasiphae',
    parent: 'jupiter',
    radiusKm: 28.9,
    rotationHours: 17626.1,
    orbitKm: 23463200,
    orbitDays: 734.4215,
    orbitInclDeg: 148.3,
    orbitEcc: 0.412,
    craterFreq: 55,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.65,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'sponde',
    name: 'Sponde',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 17710.9,
    orbitKm: 23538700,
    orbitDays: 737.9542,
    orbitInclDeg: 149.4,
    orbitEcc: 0.323,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'megaclite',
    name: 'Megaclite',
    parent: 'jupiter',
    radiusKm: 3.0,
    rotationHours: 17826.5,
    orbitKm: 23640100,
    orbitDays: 742.7715,
    orbitInclDeg: 149.9,
    orbitEcc: 0.421,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'cyllene',
    name: 'Cyllene',
    parent: 'jupiter',
    radiusKm: 1.0,
    rotationHours: 17836.9,
    orbitKm: 23650000,
    orbitDays: 743.2062,
    orbitInclDeg: 146.8,
    orbitEcc: 0.421,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'sinope',
    name: 'Sinope',
    parent: 'jupiter',
    radiusKm: 17.5,
    rotationHours: 17870.3,
    orbitKm: 23679300,
    orbitDays: 744.5951,
    // Red, and inclined some nine degrees away from Pasiphae, so it may be an
    // independent capture rather than a fragment of that family.
    orbitInclDeg: 157.3,
    orbitEcc: 0.262,
    craterFreq: 45,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.29,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'aoede',
    name: 'Aoede',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 17977.7,
    orbitKm: 23773100,
    orbitDays: 749.0708,
    orbitInclDeg: 155.7,
    orbitEcc: 0.437,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'autonoe',
    name: 'Autonoe',
    parent: 'jupiter',
    radiusKm: 2.0,
    rotationHours: 17990.6,
    orbitKm: 23785200,
    orbitDays: 749.6097,
    orbitInclDeg: 150.7,
    orbitEcc: 0.326,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'callirrhoe',
    name: 'Callirrhoe',
    parent: 'jupiter',
    radiusKm: 4.8,
    rotationHours: 17995.0,
    orbitKm: 23789400,
    orbitDays: 749.791,
    orbitInclDeg: 144.9,
    orbitEcc: 0.29,
    craterFreq: 28,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'kore',
    name: 'Kore',
    parent: 'jupiter',
    radiusKm: 1.0,
    // The outermost of Jupiter's named moons, over 24 million km out and barely
    // held.
    rotationHours: 18466.2,
    orbitKm: 24203300,
    orbitDays: 769.4229,
    orbitInclDeg: 141.7,
    orbitEcc: 0.338,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // Saturn's ring moons. All of these are continually resurfaced by ring
  // material, which fills in craters and leaves them among the brightest and
  // smoothest objects anywhere; Atlas, Pan and Daphnis have accreted equatorial
  // ridges that make them look like flying saucers.
  {
    key: 'pan',
    name: 'Pan',
    parent: 'saturn',
    radiusKm: 14.0,
    rotationHours: 13.8012,
    orbitKm: 133600,
    orbitDays: 0.575051,
    craterFreq: 34,
    craterOctaves: 3,
    craterDepth: 0.06,
    craterDensity: 0.2,
    roughness: 0.3,
    photometry: 0.6,
    albedoBoost: 2.0,
  },
  {
    key: 'daphnis',
    name: 'Daphnis',
    parent: 'saturn',
    radiusKm: 3.8,
    rotationHours: 14.2579,
    orbitKm: 136500,
    orbitDays: 0.59408,
    craterFreq: 24,
    craterOctaves: 3,
    craterDepth: 0.06,
    craterDensity: 0.2,
    roughness: 0.3,
    photometry: 0.6,
    albedoBoost: 2.0,
  },
  {
    key: 'atlas',
    name: 'Atlas',
    parent: 'saturn',
    radiusKm: 15.1,
    rotationHours: 14.5104,
    orbitKm: 137700,
    orbitDays: 0.604602,
    craterFreq: 34,
    craterOctaves: 3,
    craterDepth: 0.06,
    craterDensity: 0.2,
    roughness: 0.3,
    photometry: 0.6,
    albedoBoost: 2.0,
  },
  {
    key: 'prometheus',
    name: 'Prometheus',
    parent: 'saturn',
    radiusKm: 43.1,
    rotationHours: 14.7811,
    orbitKm: 139400,
    orbitDays: 0.615878,
    // Very elongated — 137 by 56 km — and porous enough that its density is
    // under half that of water.
    craterFreq: 60,
    craterOctaves: 5,
    craterDepth: 0.14,
    craterDensity: 0.45,
    roughness: 0.28,
    photometry: 0.9,
    albedoBoost: 1.9,
  },
  {
    key: 'pandora',
    name: 'Pandora',
    parent: 'saturn',
    radiusKm: 40.6,
    rotationHours: 15.1529,
    orbitKm: 141700,
    orbitDays: 0.631369,
    // More cratered than Prometheus, with the larger basins partly filled by
    // drifted ring dust.
    craterFreq: 60,
    craterOctaves: 5,
    craterDepth: 0.16,
    craterDensity: 0.55,
    roughness: 0.26,
    photometry: 0.9,
    albedoBoost: 1.9,
  },
  {
    key: 'epimetheus',
    name: 'Epimetheus',
    parent: 'saturn',
    radiusKm: 58.2,
    rotationHours: 16.7283,
    orbitKm: 151400,
    orbitDays: 0.697012,
    orbitInclDeg: 0.3,
    // Epimetheus and Janus share an orbit and swap places every four years, the
    // only pair in the solar system that does this; the fifty kilometres between
    // their semi-major axes is less than either body's own diameter.
    craterFreq: 70,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.22,
    photometry: 1,
    albedoBoost: 1.85,
  },
  {
    key: 'janus',
    name: 'Janus',
    parent: 'saturn',
    radiusKm: 89.2,
    rotationHours: 16.7365,
    orbitKm: 151500,
    orbitDays: 0.697353,
    orbitInclDeg: 0.2,
    craterFreq: 85,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.2,
    photometry: 1,
    albedoBoost: 1.85,
  },
  {
    key: 'aegaeon',
    name: 'Aegaeon',
    parent: 'saturn',
    radiusKm: 0.33,
    rotationHours: 19.3948,
    orbitKm: 167500,
    orbitDays: 0.808115,
    // A third of a kilometre across, embedded in the faint G ring arc it
    // presumably sources. Too small to hold a crater worth rendering.
    craterFreq: 14,
    craterOctaves: 2,
    craterDepth: 0.05,
    craterDensity: 0.15,
    roughness: 0.32,
    photometry: 0.5,
    albedoBoost: 1.9,
  },
  {
    key: 'mimas',
    name: 'Mimas',
    parent: 'saturn',
    radiusKm: 198.2,
    rotationHours: 22.6181,
    orbitKm: 186000,
    orbitDays: 0.942422,
    orbitInclDeg: 1.6,
    // Herschel is 130 km across on a 198 km body: the impact that made it came
    // close to breaking Mimas apart, and the crater is a tenth of the moon's
    // circumference wide. Otherwise saturation cratered clean ice.
    craterFreq: 150,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.68,
    roughness: 0.07,
    photometry: 1,
    albedoBoost: 2.0,
  },
  {
    key: 'methone',
    name: 'Methone',
    parent: 'saturn',
    radiusKm: 1.45,
    rotationHours: 24.2292,
    orbitKm: 194700,
    orbitDays: 1.009549,
    // Featureless: Cassini found an egg-shaped body with no craters at all, its
    // surface a smooth mantle of ice dust swept up from the E ring.
    craterFreq: 16,
    craterOctaves: 1,
    craterDepth: 0.02,
    craterDensity: 0.04,
    roughness: 0.04,
    photometry: 0.4,
    albedoBoost: 2.1,
  },
  {
    key: 'anthe',
    name: 'Anthe',
    parent: 'saturn',
    radiusKm: 0.9,
    rotationHours: 24.9336,
    orbitKm: 198100,
    orbitDays: 1.038898,
    craterFreq: 14,
    craterOctaves: 1,
    craterDepth: 0.02,
    craterDensity: 0.05,
    roughness: 0.06,
    photometry: 0.4,
    albedoBoost: 2.1,
  },
  {
    key: 'pallene',
    name: 'Pallene',
    parent: 'saturn',
    radiusKm: 2.22,
    rotationHours: 27.7454,
    orbitKm: 212300,
    orbitDays: 1.156059,
    orbitInclDeg: 0.2,
    // Smooth like Methone and for the same reason.
    craterFreq: 18,
    craterOctaves: 1,
    craterDepth: 0.02,
    craterDensity: 0.05,
    roughness: 0.05,
    photometry: 0.4,
    albedoBoost: 2.1,
  },
  {
    key: 'telesto',
    name: 'Telesto',
    parent: 'saturn',
    radiusKm: 12.4,
    // Telesto and Calypso are trojans of Tethys, sitting in its leading and
    // trailing Lagrange points, so all three share one orbit and one period.
    rotationHours: 45.3072,
    orbitKm: 295000,
    orbitDays: 1.887802,
    orbitInclDeg: 1.2,
    craterFreq: 32,
    craterOctaves: 4,
    craterDepth: 0.1,
    craterDensity: 0.3,
    roughness: 0.24,
    photometry: 0.7,
    albedoBoost: 2.0,
  },
  {
    key: 'calypso',
    name: 'Calypso',
    parent: 'saturn',
    radiusKm: 10.7,
    rotationHours: 45.3073,
    orbitKm: 295000,
    orbitDays: 1.887803,
    orbitInclDeg: 1.5,
    craterFreq: 30,
    craterOctaves: 4,
    craterDepth: 0.1,
    craterDensity: 0.3,
    roughness: 0.26,
    photometry: 0.7,
    albedoBoost: 2.0,
  },
  {
    key: 'helene',
    name: 'Helene',
    parent: 'saturn',
    radiusKm: 18.0,
    // A trojan of Dione, in the leading Lagrange point.
    rotationHours: 65.686,
    orbitKm: 377600,
    orbitDays: 2.736916,
    craterFreq: 36,
    craterOctaves: 4,
    craterDepth: 0.09,
    craterDensity: 0.28,
    // Half the surface is buried under metres of drifted ice dust that has run
    // downhill into gully-like channels, leaving it strangely soft-edged.
    roughness: 0.14,
    photometry: 0.6,
    albedoBoost: 2.0,
  },
  {
    key: 'polydeuces',
    name: 'Polydeuces',
    parent: 'saturn',
    radiusKm: 1.3,
    // Dione's trailing trojan, and it librates enormously — wandering tens of
    // degrees either side of the Lagrange point over a couple of years.
    rotationHours: 65.686,
    orbitKm: 377600,
    orbitDays: 2.736916,
    craterFreq: 14,
    craterOctaves: 2,
    craterDepth: 0.04,
    craterDensity: 0.1,
    roughness: 0.1,
    photometry: 0.4,
    albedoBoost: 2.0,
  },
  {
    key: 'hyperion',
    name: 'Hyperion',
    parent: 'saturn',
    radiusKm: 135.0,
    // Not locked and not even periodic: Hyperion's elongated shape and eccentric
    // orbit next to Titan leave its spin genuinely chaotic, tumbling on a
    // timescale of about thirteen days with no fixed axis.
    rotationHours: 312.0,
    orbitKm: 1481500,
    orbitDays: 21.276658,
    orbitInclDeg: 0.6,
    orbitEcc: 0.105,
    // The strangest surface in the Saturn system: density half that of water, so
    // impactors compress rather than excavate, leaving deep sharp-rimmed pits
    // over most of the moon rather than ordinary bowl craters.
    craterFreq: 90,
    craterOctaves: 6,
    craterDepth: 0.4,
    craterDensity: 0.8,
    roughness: 0.2,
    photometry: 1,
    // Dark red dust has collected in the bottom of every pit, dragging the
    // albedo down to about 0.3 — dim for Saturnian ice.
    albedoBoost: 1.1,
  },

  // The Inuit group: prograde captures near 48 degrees inclination, in three
  // subgroups around Kiviuq, Paaliaq and Siarnaq. They are uniformly light red.
  {
    key: 'kiviuq',
    name: 'Kiviuq',
    parent: 'saturn',
    radiusKm: 8.5,
    // Measured spin. The light curve varies by a factor of two, which for a body
    // this small suggests a contact binary rather than a spheroid.
    rotationHours: 21.97,
    orbitKm: 11307400,
    orbitDays: 448.9076,
    orbitInclDeg: 48.0,
    orbitEcc: 0.275,
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'ijiraq',
    name: 'Ijiraq',
    parent: 'saturn',
    radiusKm: 6.5,
    rotationHours: 10826.9,
    orbitKm: 11344700,
    orbitDays: 451.1201,
    orbitInclDeg: 49.2,
    orbitEcc: 0.293,
    craterFreq: 28,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'phoebe',
    name: 'Phoebe',
    parent: 'saturn',
    radiusKm: 106.5,
    // Measured spin, nine and a quarter hours, nothing like its 550-day orbit.
    rotationHours: 9.2735,
    orbitKm: 12929400,
    orbitDays: 550.30391,
    // Retrograde and steeply inclined. Phoebe is dense, dark and spectrally
    // unlike anything that formed near Saturn — almost certainly a captured
    // Kuiper belt object, and the source of the dark material coating one side
    // of Iapetus.
    orbitInclDeg: 175.2,
    orbitEcc: 0.164,
    // Large enough to have relaxed into a sphere once and then been battered out
    // of it; Jason is 100 km across on a 107 km body.
    craterFreq: 100,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.7,
    roughness: 0.18,
    photometry: 1,
    // Albedo 0.06. Bright ice shows in the crater walls where impacts have cut
    // through the dark carbonaceous crust, but the surface as a whole is soot.
    albedoBoost: 0.6,
  },
  {
    key: 'paaliaq',
    name: 'Paaliaq',
    parent: 'saturn',
    radiusKm: 12.5,
    rotationHours: 16457.2,
    orbitKm: 14997700,
    orbitDays: 685.7153,
    orbitInclDeg: 48.5,
    orbitEcc: 0.378,
    craterFreq: 34,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'skathi',
    name: 'Skathi',
    parent: 'saturn',
    radiusKm: 4.0,
    rotationHours: 17417.6,
    orbitKm: 15575400,
    orbitDays: 725.7313,
    orbitInclDeg: 151.6,
    orbitEcc: 0.281,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'albiorix',
    name: 'Albiorix',
    parent: 'saturn',
    radiusKm: 14.3,
    // Measured spin. Largest of the Gallic group, a set of prograde captures
    // near 37 degrees that are redder than the Inuit moons.
    rotationHours: 13.33,
    orbitKm: 16329200,
    orbitDays: 779.0701,
    orbitInclDeg: 36.8,
    orbitEcc: 0.482,
    craterFreq: 36,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'bebhionn',
    name: 'Bebhionn',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 19911.4,
    orbitKm: 17027300,
    orbitDays: 829.6437,
    orbitInclDeg: 38.6,
    orbitEcc: 0.459,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'erriapus',
    name: 'Erriapus',
    parent: 'saturn',
    radiusKm: 5.0,
    rotationHours: 20758.2,
    orbitKm: 17506900,
    orbitDays: 864.9236,
    orbitInclDeg: 37.1,
    orbitEcc: 0.475,
    craterFreq: 26,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'skoll',
    name: 'Skoll',
    parent: 'saturn',
    radiusKm: 2.5,
    rotationHours: 20965.8,
    orbitKm: 17623400,
    orbitDays: 873.5736,
    orbitInclDeg: 159.4,
    orbitEcc: 0.463,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'tarqeq',
    name: 'Tarqeq',
    parent: 'saturn',
    radiusKm: 3.5,
    rotationHours: 21188.4,
    orbitKm: 17751000,
    orbitDays: 882.8514,
    orbitInclDeg: 48.7,
    orbitEcc: 0.144,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'siarnaq',
    name: 'Siarnaq',
    parent: 'saturn',
    radiusKm: 19.7,
    // Measured spin. The largest of the Inuit group and of all Saturn's prograde
    // irregulars.
    rotationHours: 10.19,
    orbitKm: 17881100,
    orbitDays: 892.6799,
    orbitInclDeg: 47.8,
    orbitEcc: 0.308,
    craterFreq: 44,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'tarvos',
    name: 'Tarvos',
    parent: 'saturn',
    radiusKm: 7.5,
    rotationHours: 22031.6,
    orbitKm: 18216600,
    orbitDays: 917.984,
    orbitInclDeg: 37.8,
    orbitEcc: 0.522,
    craterFreq: 28,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'hyrrokkin',
    name: 'Hyrrokkin',
    parent: 'saturn',
    radiusKm: 4.0,
    rotationHours: 22259.0,
    orbitKm: 18340900,
    orbitDays: 927.4569,
    orbitInclDeg: 149.9,
    orbitEcc: 0.336,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'greip',
    name: 'Greip',
    parent: 'saturn',
    radiusKm: 2.5,
    rotationHours: 22330.5,
    orbitKm: 18380000,
    orbitDays: 930.4389,
    orbitInclDeg: 174.2,
    orbitEcc: 0.317,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'mundilfari',
    name: 'Mundilfari',
    parent: 'saturn',
    radiusKm: 3.5,
    rotationHours: 22711.0,
    orbitKm: 18588200,
    orbitDays: 946.2903,
    // Largest member of the most populous of the retrograde Norse subgroups,
    // whose several dozen tiny members all look like debris from one body broken
    // up within the last hundred million years.
    orbitInclDeg: 167.1,
    orbitEcc: 0.211,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'gridr',
    name: 'Gridr',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 23936.0,
    orbitKm: 19250600,
    orbitDays: 997.3319,
    orbitInclDeg: 163.9,
    orbitEcc: 0.187,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'bergelmir',
    name: 'Bergelmir',
    parent: 'saturn',
    radiusKm: 2.5,
    rotationHours: 23966.8,
    orbitKm: 19268100,
    orbitDays: 998.6187,
    orbitInclDeg: 158.8,
    orbitEcc: 0.145,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'jarnsaxa',
    name: 'Jarnsaxa',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 23979.1,
    orbitKm: 19273500,
    orbitDays: 999.1271,
    orbitInclDeg: 163.0,
    orbitEcc: 0.218,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'narvi',
    name: 'Narvi',
    parent: 'saturn',
    radiusKm: 3.5,
    rotationHours: 23998.6,
    orbitKm: 19285000,
    orbitDays: 999.9417,
    orbitInclDeg: 142.2,
    orbitEcc: 0.441,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'suttungr',
    name: 'Suttungr',
    parent: 'saturn',
    radiusKm: 3.5,
    rotationHours: 24197.9,
    orbitKm: 19391900,
    orbitDays: 1008.2451,
    orbitInclDeg: 175.7,
    orbitEcc: 0.116,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'hati',
    name: 'Hati',
    parent: 'saturn',
    radiusKm: 2.5,
    rotationHours: 24768.6,
    orbitKm: 19695000,
    orbitDays: 1032.0236,
    orbitInclDeg: 165.4,
    orbitEcc: 0.372,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'eggther',
    name: 'Eggther',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 25051.3,
    orbitKm: 19844600,
    orbitDays: 1043.8035,
    orbitInclDeg: 165.0,
    orbitEcc: 0.157,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'farbauti',
    name: 'Farbauti',
    parent: 'saturn',
    radiusKm: 2.5,
    rotationHours: 25899.0,
    orbitKm: 20290700,
    orbitDays: 1079.1243,
    orbitInclDeg: 156.2,
    orbitEcc: 0.249,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'thrymr',
    name: 'Thrymr',
    parent: 'saturn',
    radiusKm: 4.0,
    rotationHours: 25973.5,
    orbitKm: 20330500,
    orbitDays: 1082.2292,
    orbitInclDeg: 175.0,
    orbitEcc: 0.467,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'bestla',
    name: 'Bestla',
    parent: 'saturn',
    radiusKm: 3.5,
    rotationHours: 25990.7,
    orbitKm: 20337800,
    orbitDays: 1082.9444,
    orbitInclDeg: 138.3,
    orbitEcc: 0.486,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'angrboda',
    name: 'Angrboda',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 26476.8,
    orbitKm: 20591500,
    orbitDays: 1103.1986,
    // Almost exactly polar-retrograde: 178 degrees, so it runs backwards in
    // nearly the same plane as the regular moons run forwards.
    orbitInclDeg: 177.7,
    orbitEcc: 0.216,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'aegir',
    name: 'Aegir',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 26619.1,
    orbitKm: 20664400,
    orbitDays: 1109.1278,
    orbitInclDeg: 166.1,
    orbitEcc: 0.255,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'beli',
    name: 'Beli',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 26694.4,
    orbitKm: 20703700,
    orbitDays: 1112.2687,
    orbitInclDeg: 158.9,
    orbitEcc: 0.087,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'gerd',
    name: 'Gerd',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 27165.7,
    orbitKm: 20947500,
    orbitDays: 1131.9062,
    orbitInclDeg: 174.4,
    orbitEcc: 0.517,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'gunnlod',
    name: 'Gunnlod',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 27545.6,
    orbitKm: 21141800,
    orbitDays: 1147.7354,
    orbitInclDeg: 160.4,
    orbitEcc: 0.251,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'skrymir',
    name: 'Skrymir',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 28145.3,
    orbitKm: 21447400,
    orbitDays: 1172.7215,
    orbitInclDeg: 175.6,
    orbitEcc: 0.437,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'alvaldi',
    name: 'Alvaldi',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 29227.3,
    orbitKm: 21993800,
    orbitDays: 1217.8042,
    orbitInclDeg: 177.4,
    orbitEcc: 0.238,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'kari',
    name: 'Kari',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 29303.4,
    orbitKm: 22032100,
    orbitDays: 1220.9757,
    // Namesake of a tight retrograde clump between 152 and 157 degrees, likely
    // another collisional family.
    orbitInclDeg: 153.0,
    orbitEcc: 0.469,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'geirrod',
    name: 'Geirrod',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 29761.1,
    orbitKm: 22259400,
    orbitDays: 1240.0465,
    orbitInclDeg: 154.4,
    orbitEcc: 0.539,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'fenrir',
    name: 'Fenrir',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 29902.1,
    orbitKm: 22330800,
    orbitDays: 1245.9215,
    orbitInclDeg: 164.5,
    orbitEcc: 0.137,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'surtur',
    name: 'Surtur',
    parent: 'saturn',
    radiusKm: 3.0,
    rotationHours: 30747.4,
    orbitKm: 22748000,
    orbitDays: 1281.1396,
    orbitInclDeg: 168.4,
    orbitEcc: 0.448,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'loge',
    name: 'Loge',
    parent: 'saturn',
    radiusKm: 2.5,
    rotationHours: 31092.6,
    orbitKm: 22919200,
    orbitDays: 1295.5243,
    orbitInclDeg: 168.1,
    orbitEcc: 0.191,
    craterFreq: 22,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'ymir',
    name: 'Ymir',
    parent: 'saturn',
    radiusKm: 9.5,
    // Measured spin. Largest of the Norse group after Phoebe.
    rotationHours: 11.93,
    orbitKm: 22955600,
    orbitDays: 1298.6819,
    orbitInclDeg: 172.3,
    orbitEcc: 0.338,
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'thiazzi',
    name: 'Thiazzi',
    parent: 'saturn',
    radiusKm: 2.0,
    rotationHours: 32444.0,
    orbitKm: 23577500,
    orbitDays: 1351.8319,
    orbitInclDeg: 158.8,
    orbitEcc: 0.511,
    craterFreq: 20,
    craterOctaves: 4,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.34,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'fornjot',
    name: 'Fornjot',
    parent: 'saturn',
    radiusKm: 3.0,
    // Outermost named Saturnian moon, twenty-five million kilometres out and
    // four years to the orbit.
    rotationHours: 35288.7,
    orbitKm: 24936800,
    orbitDays: 1470.3618,
    orbitInclDeg: 170.0,
    orbitEcc: 0.213,
    craterFreq: 24,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.33,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // Uranus's inner moons: thirteen small dark bodies packed inside Miranda's
  // orbit, tangled up with the rings and with each other. The Portia and Belinda
  // groups are close enough together that the system is chaotic on a timescale
  // of millions of years — Desdemona will probably hit Cressida, and Cupid
  // Belinda, well before the Sun leaves the main sequence.
  {
    key: 'cordelia',
    name: 'Cordelia',
    parent: 'uranus',
    radiusKm: 20.0,
    rotationHours: 8.0328,
    orbitKm: 49755,
    orbitDays: 0.3347,
    orbitInclDeg: 0.2,
    // Inner shepherd of the epsilon ring, with Ophelia outside it.
    craterFreq: 45,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'ophelia',
    name: 'Ophelia',
    parent: 'uranus',
    radiusKm: 21.5,
    rotationHours: 9.0336,
    orbitKm: 53765,
    orbitDays: 0.3764,
    orbitInclDeg: 0.2,
    craterFreq: 45,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'bianca',
    name: 'Bianca',
    parent: 'uranus',
    radiusKm: 25.5,
    rotationHours: 10.4328,
    orbitKm: 59170,
    orbitDays: 0.4347,
    orbitInclDeg: 2.3,
    craterFreq: 50,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'cressida',
    name: 'Cressida',
    parent: 'uranus',
    radiusKm: 40.0,
    rotationHours: 11.1336,
    orbitKm: 61770,
    orbitDays: 0.4639,
    orbitInclDeg: 1.8,
    craterFreq: 60,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.24,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'desdemona',
    name: 'Desdemona',
    parent: 'uranus',
    radiusKm: 32.0,
    rotationHours: 11.3664,
    orbitKm: 62663,
    orbitDays: 0.4736,
    orbitInclDeg: 3.1,
    craterFreq: 55,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'juliet',
    name: 'Juliet',
    parent: 'uranus',
    radiusKm: 47.0,
    rotationHours: 11.8344,
    orbitKm: 64362,
    orbitDays: 0.4931,
    orbitInclDeg: 3.0,
    // Voyager resolved it as strongly elongated, 150 by 74 km.
    craterFreq: 65,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'portia',
    name: 'Portia',
    parent: 'uranus',
    radiusKm: 67.5,
    rotationHours: 12.3168,
    orbitKm: 66101,
    orbitDays: 0.5132,
    orbitInclDeg: 2.7,
    craterFreq: 80,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.22,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'rosalind',
    name: 'Rosalind',
    parent: 'uranus',
    radiusKm: 36.0,
    rotationHours: 13.3992,
    orbitKm: 69930,
    orbitDays: 0.5583,
    orbitInclDeg: 1.7,
    craterFreq: 55,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'cupid',
    name: 'Cupid',
    parent: 'uranus',
    radiusKm: 9.0,
    rotationHours: 14.7,
    orbitKm: 74396,
    orbitDays: 0.6125,
    orbitInclDeg: 2.0,
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'belinda',
    name: 'Belinda',
    parent: 'uranus',
    radiusKm: 45.0,
    rotationHours: 14.9664,
    orbitKm: 75258,
    orbitDays: 0.6236,
    orbitInclDeg: 1.4,
    craterFreq: 60,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'perdita',
    name: 'Perdita',
    parent: 'uranus',
    radiusKm: 15.0,
    // Sat unnoticed in the Voyager 2 images for thirteen years before anyone
    // picked it out of them.
    rotationHours: 15.3168,
    orbitKm: 76418,
    orbitDays: 0.6382,
    orbitInclDeg: 1.6,
    craterFreq: 36,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'puck',
    name: 'Puck',
    parent: 'uranus',
    radiusKm: 81.0,
    rotationHours: 18.284,
    orbitKm: 86007,
    orbitDays: 0.761833,
    orbitInclDeg: 0.3,
    // Large enough to be nearly round, and the only inner Uranian moon Voyager
    // resolved well: three named craters on a dark, battered surface.
    craterFreq: 90,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.16,
    photometry: 1,
    albedoBoost: 0.7,
  },
  {
    key: 'mab',
    name: 'Mab',
    parent: 'uranus',
    radiusKm: 9.0,
    rotationHours: 22.1496,
    orbitKm: 97737,
    orbitDays: 0.9229,
    orbitInclDeg: 1.8,
    // Source of the outermost mu ring, which it presumably feeds with dust
    // knocked off by micrometeorites.
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.9,
  },
  {
    key: 'miranda',
    name: 'Miranda',
    parent: 'uranus',
    radiusKm: 235.8,
    rotationHours: 33.9235,
    orbitKm: 129846,
    orbitDays: 1.413479,
    // Four degrees is a lot for a regular satellite this close in, and it is
    // probably the fossil of an old resonance passage — the same episode that
    // may have heated Miranda enough to produce the coronae.
    orbitInclDeg: 4.4,
    craterFreq: 200,
    craterOctaves: 5,
    craterDepth: 0.15,
    craterDensity: 0.4,
    roughness: 0.14,
    photometry: 0.9,
    albedoBoost: 1.3,
    // The coronae and Verona Rupes: grooved ovoid provinces and a scarp with
    // twenty kilometres of relief, the tallest cliff known, on a body only 236
    // km in radius.
    fractureFreq: 45,
    fractureOctaves: 3,
    fractureDepth: 0.14,
    fractureWidth: 0.12,
    fractureTint: 0.08,
  },
  {
    key: 'ariel',
    name: 'Ariel',
    parent: 'uranus',
    radiusKm: 578.9,
    rotationHours: 60.4891,
    orbitKm: 190929,
    orbitDays: 2.520379,
    // The youngest and brightest surface of the five: resurfaced, with graben
    // floors that look flooded by something viscous.
    craterFreq: 300,
    craterOctaves: 5,
    craterDepth: 0.13,
    craterDensity: 0.3,
    roughness: 0.08,
    photometry: 0.9,
    albedoBoost: 1.45,
    fractureFreq: 50,
    fractureOctaves: 3,
    fractureDepth: 0.1,
    fractureWidth: 0.14,
    fractureTint: 0.1,
  },
  {
    key: 'umbriel',
    name: 'Umbriel',
    parent: 'uranus',
    radiusKm: 584.7,
    rotationHours: 99.4602,
    orbitKm: 265986,
    orbitDays: 4.144177,
    // The darkest and most uniformly cratered of the Uranian moons, with nothing
    // to suggest it was ever resurfaced. Wunda, a bright ring on the equator, is
    // the only feature that breaks it up.
    craterFreq: 300,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.68,
    roughness: 0.07,
    photometry: 1,
    // Albedo 0.21, about half Ariel's, for reasons nobody has explained.
    albedoBoost: 1.0,
  },
  {
    key: 'titania',
    name: 'Titania',
    parent: 'uranus',
    radiusKm: 788.9,
    rotationHours: 208.9409,
    orbitKm: 436298,
    orbitDays: 8.705869,
    craterFreq: 320,
    craterOctaves: 6,
    craterDepth: 0.16,
    craterDensity: 0.45,
    roughness: 0.08,
    photometry: 0.95,
    albedoBoost: 1.2,
    // The Messina Chasmata system, 1500 km of rift running from the equator
    // nearly to the pole.
    fractureFreq: 38,
    fractureOctaves: 2,
    fractureDepth: 0.1,
    fractureWidth: 0.15,
  },
  {
    key: 'oberon',
    name: 'Oberon',
    parent: 'uranus',
    radiusKm: 761.4,
    rotationHours: 323.1177,
    orbitKm: 583511,
    orbitDays: 13.463237,
    // Saturation cratered, with dark deposits on several crater floors.
    craterFreq: 310,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.66,
    roughness: 0.08,
    photometry: 1,
    albedoBoost: 1.1,
  },

  // Uranus's irregular moons. Francisco is the innermost irregular satellite of
  // any planet; all but Margaret are retrograde. The inclinations below are
  // against the ecliptic, as published, not against Uranus's own 98-degree
  // equator.
  {
    key: 'francisco',
    name: 'Francisco',
    parent: 'uranus',
    radiusKm: 11.0,
    rotationHours: 6408.0,
    orbitKm: 4275700,
    orbitDays: 267.0,
    orbitInclDeg: 146.8,
    orbitEcc: 0.144,
    craterFreq: 32,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'caliban',
    name: 'Caliban',
    parent: 'uranus',
    radiusKm: 21.0,
    // Measured spin, under three hours, close to the limit at which a rubble
    // pile this size would fly apart.
    rotationHours: 2.7,
    orbitKm: 7167000,
    orbitDays: 580.0,
    orbitInclDeg: 141.4,
    orbitEcc: 0.2,
    craterFreq: 45,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'stephano',
    name: 'Stephano',
    parent: 'uranus',
    radiusKm: 16.0,
    rotationHours: 16248.0,
    orbitKm: 7951400,
    orbitDays: 677.0,
    orbitInclDeg: 143.6,
    orbitEcc: 0.235,
    craterFreq: 38,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'trinculo',
    name: 'Trinculo',
    parent: 'uranus',
    radiusKm: 9.0,
    rotationHours: 17976.0,
    orbitKm: 8502600,
    orbitDays: 749.0,
    orbitInclDeg: 167.1,
    orbitEcc: 0.22,
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'sycorax',
    name: 'Sycorax',
    parent: 'uranus',
    radiusKm: 78.5,
    // Measured spin. By far the largest of Uranus's captured moons, and notably
    // red — redder than the other irregulars here.
    rotationHours: 3.6,
    orbitKm: 12193200,
    orbitDays: 1286.0,
    orbitInclDeg: 157.0,
    orbitEcc: 0.52,
    craterFreq: 90,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.68,
    roughness: 0.2,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'margaret',
    name: 'Margaret',
    parent: 'uranus',
    radiusKm: 10.0,
    rotationHours: 39720.0,
    orbitKm: 14425000,
    orbitDays: 1655.0,
    // The only prograde irregular Uranus has, and the most eccentric orbit of
    // any known moon in the solar system bar Nereid.
    orbitInclDeg: 60.5,
    orbitEcc: 0.642,
    craterFreq: 30,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'prospero',
    name: 'Prospero',
    parent: 'uranus',
    radiusKm: 25.0,
    rotationHours: 47376.0,
    orbitKm: 16221000,
    orbitDays: 1974.0,
    orbitInclDeg: 149.4,
    orbitEcc: 0.441,
    craterFreq: 48,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'setebos',
    name: 'Setebos',
    parent: 'uranus',
    radiusKm: 23.5,
    rotationHours: 53160.0,
    orbitKm: 17519800,
    orbitDays: 2215.0,
    orbitInclDeg: 153.9,
    orbitEcc: 0.579,
    craterFreq: 48,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'ferdinand',
    name: 'Ferdinand',
    parent: 'uranus',
    radiusKm: 10.5,
    rotationHours: 66912.0,
    orbitKm: 20421400,
    orbitDays: 2788.0,
    orbitInclDeg: 169.2,
    orbitEcc: 0.395,
    craterFreq: 32,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.6,
    roughness: 0.32,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // Neptune's inner moons are not original: Triton's capture wrecked whatever
  // was there, and these were reaccreted from the rubble once its orbit had
  // circularised. All but the outer two orbit faster than Neptune turns, so all
  // but the outer two are spiralling in.
  {
    key: 'naiad',
    name: 'Naiad',
    parent: 'neptune',
    radiusKm: 29.0,
    rotationHours: 7.0555,
    orbitKm: 48200,
    orbitDays: 0.29398,
    // Nearly five degrees out of Neptune's equator, which is extraordinary this
    // close in; it is held there by a resonance with Thalassa.
    orbitInclDeg: 4.7,
    craterFreq: 50,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'thalassa',
    name: 'Thalassa',
    parent: 'neptune',
    radiusKm: 40.0,
    rotationHours: 7.4659,
    orbitKm: 50100,
    orbitDays: 0.311078,
    orbitInclDeg: 0.2,
    craterFreq: 55,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'despina',
    name: 'Despina',
    parent: 'neptune',
    radiusKm: 74.0,
    rotationHours: 8.0317,
    orbitKm: 52500,
    orbitDays: 0.334656,
    // Orbits just inside the Le Verrier ring and probably shepherds it.
    craterFreq: 80,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'galatea',
    name: 'Galatea',
    parent: 'neptune',
    radiusKm: 79.0,
    rotationHours: 10.2899,
    orbitKm: 62000,
    orbitDays: 0.428744,
    // Its resonances confine the five bright arcs in the Adams ring, which is
    // the only reason a ring 50 km wide has survived.
    craterFreq: 85,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.62,
    roughness: 0.26,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'larissa',
    name: 'Larissa',
    parent: 'neptune',
    radiusKm: 96.0,
    rotationHours: 13.3197,
    orbitKm: 73500,
    orbitDays: 0.554989,
    orbitInclDeg: 0.2,
    craterFreq: 90,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.65,
    roughness: 0.24,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'hippocamp',
    name: 'Hippocamp',
    parent: 'neptune',
    radiusKm: 17.4,
    rotationHours: 22.8094,
    orbitKm: 105300,
    orbitDays: 0.95039,
    orbitInclDeg: 0.3,
    // A thousand times smaller than Proteus and sitting just inside it, which
    // suggests it is a chip knocked off Proteus by the impact that made Pharos.
    craterFreq: 36,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.6,
    roughness: 0.3,
    photometry: 1,
    albedoBoost: 0.65,
  },
  {
    key: 'proteus',
    name: 'Proteus',
    parent: 'neptune',
    radiusKm: 208.0,
    rotationHours: 26.9356,
    orbitKm: 117600,
    orbitDays: 1.122315,
    // Larger than Mimas but not ellipsoidal: a lumpy polyhedron with flat facets
    // 150 to 250 km across, probably because it was smashed and reassembled.
    // Pharos, its largest crater, is over 150 km wide.
    craterFreq: 130,
    craterOctaves: 6,
    craterDepth: 0.2,
    craterDensity: 0.66,
    roughness: 0.16,
    photometry: 1,
    // Albedo 0.096: dark for something this size, and grey rather than red.
    albedoBoost: 0.7,
  },
  {
    key: 'nereid',
    name: 'Nereid',
    parent: 'neptune',
    radiusKm: 170.0,
    // Measured spin, near twelve hours. Early reports of wild brightness swings
    // suggested chaotic rotation, but Kepler photometry showed the variation is
    // small.
    rotationHours: 11.52,
    orbitKm: 5513900,
    orbitDays: 360.133039,
    orbitInclDeg: 5.1,
    // Eccentricity 0.75, the most extreme of any large moon: Nereid was very
    // likely a regular satellite flung onto this orbit when Triton arrived.
    // Webb spectra look unlike any Kuiper belt object, so it probably formed
    // here rather than being captured.
    orbitEcc: 0.751,
    craterFreq: 110,
    craterOctaves: 6,
    craterDepth: 0.22,
    craterDensity: 0.68,
    // Thermal modelling puts its surface roughness up with Hyperion's.
    roughness: 0.2,
    photometry: 1,
    // Water ice is present spectroscopically, and the albedo is around 0.15 —
    // brighter than the captured irregulars, darker than clean ice.
    albedoBoost: 0.9,
  },
  {
    key: 'halimede',
    name: 'Halimede',
    parent: 'neptune',
    radiusKm: 30.5,
    rotationHours: 45096.0,
    orbitKm: 16590500,
    orbitDays: 1879.0,
    // Grey like Nereid, and the two have a roughly even chance of having
    // collided at some point, so Halimede may be a piece of it.
    orbitInclDeg: 119.6,
    orbitEcc: 0.521,
    craterFreq: 50,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'sao',
    name: 'Sao',
    parent: 'neptune',
    radiusKm: 22.0,
    rotationHours: 70056.0,
    orbitKm: 22239900,
    orbitDays: 2919.0,
    orbitInclDeg: 50.2,
    orbitEcc: 0.296,
    craterFreq: 45,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'laomedeia',
    name: 'Laomedeia',
    parent: 'neptune',
    radiusKm: 21.0,
    rotationHours: 76032.0,
    orbitKm: 23499900,
    orbitDays: 3168.0,
    orbitInclDeg: 36.9,
    orbitEcc: 0.419,
    craterFreq: 45,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'psamathe',
    name: 'Psamathe',
    parent: 'neptune',
    radiusKm: 20.0,
    rotationHours: 219576.0,
    orbitKm: 47646600,
    orbitDays: 9149.0,
    orbitInclDeg: 127.8,
    orbitEcc: 0.413,
    craterFreq: 44,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },
  {
    key: 'neso',
    name: 'Neso',
    parent: 'neptune',
    radiusKm: 30.0,
    rotationHours: 235320.0,
    // Fifty million kilometres out, twenty-seven years to the orbit: the most
    // distant named moon of any planet, held only because Neptune's Hill sphere
    // is the largest in the solar system.
    orbitKm: 49897800,
    orbitDays: 9805.0,
    orbitInclDeg: 128.4,
    orbitEcc: 0.455,
    craterFreq: 50,
    craterOctaves: 5,
    craterDepth: 0.22,
    craterDensity: 0.62,
    roughness: 0.28,
    photometry: 1,
    albedoBoost: 0.6,
  },

  // Pluto's four small moons all orbit close to the Pluto-Charon plane in a
  // near-resonant chain, and unlike almost every other small moon they are not
  // locked: they tumble fast and off-axis, because the gravity field of a binary
  // primary never lets them settle.
  {
    key: 'styx',
    name: 'Styx',
    parent: 'pluto',
    radiusKm: 5.2,
    // Measured: 3.24 days, not the 20-day orbit, and its pole lies nearly in the
    // orbital plane.
    rotationHours: 77.8,
    orbitKm: 43200,
    orbitDays: 20.16,
    craterFreq: 26,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.55,
    roughness: 0.3,
    photometry: 0.9,
    // Water ice, albedo around 0.65: these are far brighter than any captured
    // irregular, which is part of why they are thought to be debris from the
    // Charon-forming impact rather than captures.
    albedoBoost: 1.5,
  },
  {
    key: 'nix',
    name: 'Nix',
    parent: 'pluto',
    radiusKm: 18.0,
    // Tumbling: New Horizons found a 43.9-hour spin tipped almost onto its side.
    rotationHours: 43.9,
    orbitKm: 49300,
    orbitDays: 24.85,
    craterFreq: 38,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.55,
    roughness: 0.28,
    photometry: 0.9,
    albedoBoost: 1.6,
  },
  {
    key: 'kerberos',
    name: 'Kerberos',
    parent: 'pluto',
    radiusKm: 6.0,
    rotationHours: 127.4,
    orbitKm: 58300,
    orbitDays: 32.17,
    orbitInclDeg: 0.4,
    // Two lobes of roughly equal size stuck together, so it is either a contact
    // binary or the merger of two smaller fragments.
    craterFreq: 26,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.55,
    roughness: 0.32,
    photometry: 0.9,
    albedoBoost: 1.5,
  },
  {
    key: 'hydra',
    name: 'Hydra',
    parent: 'pluto',
    radiusKm: 18.5,
    // The fastest spin of the four, ten and a third hours.
    rotationHours: 10.3,
    orbitKm: 65200,
    orbitDays: 38.2,
    orbitInclDeg: 0.3,
    craterFreq: 38,
    craterOctaves: 5,
    craterDepth: 0.2,
    craterDensity: 0.55,
    roughness: 0.28,
    photometry: 0.9,
    // The brightest of Pluto's small moons, albedo around 0.8: crystalline water
    // ice, cleaner even than Nix.
    albedoBoost: 1.8,
  },
];

// A moon below a few hundred kilometres is not a sphere: its own gravity cannot
// overcome the strength of its material, so it keeps the shape its formation and
// impact history left. Most of the moons in this file have never had that shape
// resolved and the renderer invents a plausible one; the surveyed ones take the
// published figure from figures.js instead.
applyMeasuredAxes(MOONS);

export const MOON_BY_KEY = new Map(MOONS.map((m) => [m.key, m]));
